export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-4 sm:px-6 py-16">
      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-sm text-text-muted mb-10">
        Last updated 2026-09-07. Same disclaimer as the privacy page: this is
        a demo take-home project, not a real business, and this page is not
        legal advice.
      </p>
      <div className="space-y-6 text-sm text-text-muted leading-relaxed">
        <section>
          <h2 className="text-text font-semibold mb-2">No real payments</h2>
          <p>
            The Pricing page shows plans and buttons for illustration. No
            payment processor is connected, and clicking &quot;Subscribe&quot;
            will not charge you anything real. It&apos;s explicitly labeled as a
            demo on that page.
          </p>
        </section>
        <section>
          <h2 className="text-text font-semibold mb-2">Generated content</h2>
          <p>
            Content is generated by third-party models (Sana via Pollinations,
            LTX via Pixazo). Check their terms before using outputs
            commercially, since this demo makes no representations about
            licensing of anything it generates.
          </p>
        </section>
        <section>
          <h2 className="text-text font-semibold mb-2">Acceptable use</h2>
          <p>
            Don&apos;t use this to generate illegal content, attempt to
            abuse the free-tier rate limits at scale, or rely on this demo
            for anything you actually need to work reliably.
          </p>
        </section>
        <section>
          <h2 className="text-text font-semibold mb-2">No warranty</h2>
          <p>
            Provided as-is, built in a single sitting as an exercise. Things
            may break, especially video generation, which depends on a
            free-tier third-party provider (Pixazo) outside this project&apos;s
            control and could change its terms at any time.
          </p>
        </section>
      </div>
    </div>
  );
}
